CALL TASK_8.STAGING_SCHEMA.LOAD_SOURCE_DATA_TO_STAGING();
CALL TASK_8.CLEANCING_SCHEMA.LOAD_SOURCE_TO_CLEANCING_LAYER();
CALL TASK_8.CLEANCING_SCHEMA.LOAD_WRK_TABLES();
CALL TASK_8.CLEANCING_SCHEMA.UPDATE_DIM_TABLES();
CALL TASK_8.CLEANCING_SCHEMA.LOAD_FCT_TABLES();